repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: b0d1fba7ac3be53c71fb0d3211d911e629f8aecb  # frozen: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: eb210df91dacdbc9d34b9b51d4347a8ba4ac0ed3  # frozen: 0.6.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: ea38855cd396a36ac00abcda11687ef7f968fa81  # frozen: 0.6.1
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: cafd5506f18eea191804850dacc0a4264772d59d  # frozen: v3.0.0-alpha.4
    hooks:
      - id: prettier
        # .git/COMMIT_EDITMSG: commitizen needs to read this file
        # CHANGELOG.md: release-please autocreates this file, prettier would mess with it
        # docs/cli.md: prettier would destroy the required indentation
        exclude: >
          (?x)^(
            ^\.git/COMMIT_EDITMSG$|
            ^CHANGELOG\.md$|
            ^docs/cli\.md$|
          )$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 6ba454799f284b13ccd53ca2adaf4848da6d3509  # frozen: v0.0.240
    hooks:
      - id: ruff

  - repo: https://github.com/FHPythonUtils/LicenseCheck/
    rev: "5bbbb11e58d91a1df4e791f3d48e904a5a25b78d"  # frozen: 2023
    hooks:
      - id: licensecheck
        files: pyproject.toml
        args: ["--format=ansi"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 52057ace9f7e1400d560eac76065e257ee3b2213  # frozen: v2.40.0
    hooks:
      - id: commitizen
