site_name: services-test
site_description: services-test

theme: material

repo_name: afuetterer/services-test
repo_url: https://github.com/afuetterer/services-test

nav:
  - Home: index.md
  - License: license.md

plugins:
  - search
  - mkdocstrings
  - include-markdown

markdown_extensions:
  - admonition
