# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      # poetry lock is needed for the licensecheck
      - run: |
          python -m pip install -r .github/workflows/requirements.txt
          poetry lock
      # https://github.com/pre-commit/action
      # sets up pre-commit cache
      - uses: pre-commit/action@v3.0.0
      - run: |
          tox -e type

  test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        python-version: ["3.8", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -m pip install -r .github/workflows/requirements.txt
      - run: tox
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Cache .tox directory
        uses: actions/cache@v3
        with:
          path: ".tox"
          key: ${{ matrix.os }}-${{ matrix.python-version }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('pyproject.toml') }}
