# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      # poetry lock is needed for the licensecheck
      - run: |
          python -m pip install -r .github/workflows/requirements.txt
          poetry lock
      # https://github.com/pre-commit/action
      # sets up pre-commit cache
      - uses: pre-commit/action@v3.0.0
      - run: |
          tox -e type

  test:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        python-version: ["3.8", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - run: python -m pip install -r .github/workflows/requirements.txt
      - run: |
          mkdir coverage
          pwd
          ls -la
          ls -la coverage
      - run: tox
        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
      - run: |
          pwd
          ls -la
          ls -la coverage
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Cache .tox directory
        uses: actions/cache@v3
        with:
          path: ".tox"
          key: ${{ runner.os }}-${{ matrix.python-version }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('pyproject.toml') }}
      - name: Store coverage files
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  # adapted from
  # https://github.com/tiangolo/fastapi/blob/master/.github/workflows/test.yml
  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Get coverage files
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage

      - run: python -m pip install -r .github/workflows/requirements.txt
      - run: tox -e report

      # - name: Use Codecov to track coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     files: ./coverage.xml # coverage report
