# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: pwd
      - run: ls -la

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          # config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - run: ls -la
