name: Update pre-commit hooks

permissions:
  contents: read

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vrslev/pre-commit-autoupdate@v1.0.0
      - uses: peter-evans/create-pull-request@v3.11.0
        with:
          branch: pre-commit-autoupdate
          title: "chore(deps): update pre-commit hooks"
          commit-message: "chore(deps): update pre-commit hooks"
          body: Update pre-commit hooks
          labels: dependencies
          delete-branch: True
